### ISSUE TITLE
Burnwire activation relies on a single voltage reading - add a confirming reading and sanity check

### ISSUE THREAD

**Issue by MattCummings0517** [Project-CETI/whale-tag-embedded#34]
Currently the burnwire is activated when a battery cell drops below a configurable level.  A single bad reading or error may cause erroneous activation.  Bad readings have been seen occasionally on development boards.  The software should double or triple check any reading that is low enough to trigger the burnwire.

**Comment by msalinoh** [comment]
Issue resolved in #69
