### ISSUE TITLE
Add option in configuration that provides a way to disable the recovery board

### ISSUE THREAD

**Issue by MattCummings0517** [Project-CETI/whale-tag-embedded#36]
Currently recovery board power on v2.1 hardware is managed by the cetiTagApp and is turned on and off as a function of tag state (for example, it is turned off when the tag is submerged).   Having a means of completely turning the recovery board off outside of the app (either from the supervisor script tagMonitor.sh or in the configuration file config.txt) will provide flexibility.  At least two tags have broken recovery boards that still use power and thus reduce run time.

**Comment by msalinoh** [comment]
`recovery_enable` option added to runtime config file `config.txt`
