### ISSUE TITLE
Need to activate coin cell trickle charging feature

### ISSUE THREAD

**Issue by MattCummings0517** [Project-CETI/whale-tag-embedded#44]
Starting with v2.2 hardware, a lithium coin cell will be used to back up the RTC.  The RTC IC has built-in features to trickle charge the cell, but these features need to be turned on in code.  

Care may be needed to ensure there will be no issues if code with trickle charging enabled is inadvertently installed on the Tags that have been built so far with non-rechargeable batteries.

**Comment by msalinoh** [comment]
Including the command to manually enable trickle charging on v2.2 here:
`i2cset -y 1 0x68 0x09 0xAA`

**Comment by msalinoh** [comment]
RTC trickle charging enabled on firstboot for v2_3 tags
